# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test
      - name: Build with Maven
        run: mvn clean -DskipTests package
      - run: |
          mkdir -p target/artifact
          mv Dockerfile target/artifact
          mv target/*.jar target/artifact
      - uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: target/artifact
  docker:
    needs: app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: output-artifact
          path: target/artifact
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: target/artifact
          file: ./target/artifact/Dockerfile
          platforms: linux/amd64
          push: true
#          tags: ${{ steps.docker_meta.outputs.tags }}
#          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: misoboy/demo:latest

          
